### ISSUE TITLE
Mouse tip - turn off

### ISSUE THREAD

**Issue by coomsie** [CanterburyRegionalCouncil/wab-widgets#12]
Are we able to turn off the mouse tips when the user is hovering over the widget ...

see below .. as you move over the widet panel the mouse tip can land over the widget making it hard to select objects because they are not visible

![image](https://user-images.githubusercontent.com/125121/29197035-a681e7ce-7e8c-11e7-87c8-25859d0d3c76.png)

**Comment by cbs-greg** [comment]
@cristiangimenez86 - please can you take a look at this one? Is it quick and easy? Thanks.

**Comment by cristiangimenez86** [comment]
Hi Iain,

Mouse tooltips are now displayed only when the pointer is over the map.
Also, I added an extra check box to show/hide mouse tooltips.

![image](https://user-images.githubusercontent.com/5216487/29253458-eb79a992-80d1-11e7-990e-fd9d70dc25fa.png)

cheers.

**Comment by coomsie** [comment]
Great ta,

I will deploy to test…
