### ISSUE TITLE
Print Widget: Moving map in or out print layout

### ISSUE THREAD

**Issue by coomsie** [CanterburyRegionalCouncil/wab-widgets#9]
This function stops working at some point ... maybe due to other js error?
i.e.
When moving the map after grabbing the map either 

inside the print layout :
layout will stay still and move the map

outside the print layout: 
layout will move with the map ...

**Comment by cristiangimenez86** [comment]
Hi Iain,

I'm not being able to reproduce this bug.
Maybe because I've fixed the issue: PrintWidget: Errors on zoom in and out.  ?
https://github.com/CanterburyRegionalCouncil/wab-widgets/issues/7

please let me know if start happening again so I can have a look.

Cheers,
Cristian.

**Comment by coomsie** [comment]
Yeah I still can re-produce it ...

Steps
+ start the widget up
+ use it
+ then close widget window
+ start again
= cant move map with layout fixed ....

once in this mode, only way to clear the state is to re-load.

**Comment by cbs-greg** [comment]
@cristiangimenez86 - and this one please :)

**Comment by cristiangimenez86** [comment]
Hi, 

I still cannot reproduce this error in my local environment.
Could you tell me which url are you using for testing? Maybe I can have a look and try to find the error.

Cheers.
Cristian.

**Comment by coomsie** [comment]
https://mapportaltest.ecan.govt.nz/PortalApps/WAB/

Not sure if this is able to be accessed outside our network ...

**Comment by cristiangimenez86** [comment]
Yes, I have access and yes, the issue is happening on Test. I'll check to see if I can fix it.
